server {
    listen 80;
    listen [::]:80;
    server_name amy-jaffe.157.90.162.50.nip.io;

    root /var/www/amy-jaffe-nutrition;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.avif$ {
        default_type image/avif;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }

    location ~* \.(?:css|js|avif|png|jpg|jpeg|svg|webp|ico|mp4)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }
}
